Repository permissionlesstech/bitchat-android, pull requests merged in 2025-08, with the labels that each got.

#197 Feature/mentions
  app/src/main/java/com/bitchat/android/ui/ChatScreen.kt
  app/src/main/java/com/bitchat/android/ui/ChatState.kt
  app/src/main/java/com/bitchat/android/ui/ChatViewModel.kt
  app/src/main/java/com/bitchat/android/ui/CommandProcessor.kt
  app/src/main/java/com/bitchat/android/ui/InputComponents.kt
Labels: enhancement, complete, UI/UX

#170 Disable overlay bakground animation
  app/src/main/java/com/bitchat/android/ui/ChatScreen.kt
  app/src/main/java/com/bitchat/android/ui/SidebarComponents.kt
Labels: enhancement, UI/UX

#55 Add Real-Time Bluetooth State Monitoring to OnboardingFlowScreen
  app/src/main/java/com/bitchat/android/MainActivity.kt
  app/src/main/java/com/bitchat/android/onboarding/BluetoothCheckScreen.kt
  app/src/main/java/com/bitchat/android/onboarding/BluetoothStatusManager.kt
Labels: enhancement

#134 f-droid: add metadata folder
  app/build.gradle.kts
  fastlane/metadata/android/en-US/changelog/3.txt
  fastlane/metadata/android/en-US/full_description.txt
  fastlane/metadata/android/en-US/images/icon.png
  fastlane/metadata/android/en-US/short_description.txt
Labels: help wanted, build

#146 Add CommandSuggestionsBox quick access
  app/src/main/java/com/bitchat/android/ui/ChatScreen.kt
  app/src/main/java/com/bitchat/android/ui/CommandProcessor.kt
  app/src/main/java/com/bitchat/android/ui/InputComponents.kt
  app/src/main/res/values/strings.xml
Labels: UI/UX
