Repository permissionlesstech/bitchat-android, pull requests merged in 2025-07, with the labels that each got.

#42 fixes vertical padding in permission explanation
  app/src/main/java/com/bitchat/android/onboarding/PermissionExplanationScreen.kt
Labels: UI/UX

#44 feat: add monochrome icon for Android 12+
  app/src/main/res/drawable/ic_launcher_monochrome.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
Labels: enhancement, needs review, UI/UX

#57 Cheap routing optimizations
  app/src/main/java/com/bitchat/android/mesh/BluetoothConnectionManager.kt
  app/src/main/java/com/bitchat/android/mesh/BluetoothMeshService.kt
  app/src/main/java/com/bitchat/android/mesh/MessageHandler.kt
  app/src/main/java/com/bitchat/android/mesh/PacketProcessor.kt
  app/src/main/java/com/bitchat/android/mesh/SecurityManager.kt
  app/src/main/java/com/bitchat/android/model/RoutedPacket.kt
Labels: enhancement, needs review, networking

#48 Fix Android Message fragmentation for iOS compatibility
  app/src/main/java/com/bitchat/android/mesh/BluetoothConnectionManager.kt
  app/src/main/java/com/bitchat/android/mesh/BluetoothMeshService.kt
  app/src/main/java/com/bitchat/android/mesh/BluetoothPacketBroadcaster.kt
  app/src/main/java/com/bitchat/android/mesh/FragmentManager.kt
Labels: needs review, networking

#125 Bugfix: Handled single or triple clicked at once instead of executing them as separate events
  app/src/main/java/com/bitchat/android/core/ui/utils/ModifierExt.kt
  app/src/main/java/com/bitchat/android/ui/ChatHeader.kt
Labels: complete

#129 Refactor: Introduce MainViewModel for onboarding state management
  app/src/main/java/com/bitchat/android/MainActivity.kt
  app/src/main/java/com/bitchat/android/MainViewModel.kt
  app/src/main/java/com/bitchat/android/onboarding/OnboardingState.kt
Labels: complete

#136 fix: update sidebar text to use string resources
  app/src/main/java/com/bitchat/android/ui/SidebarComponents.kt
  app/src/main/res/values/strings.xml
Labels: complete

#139 refactor: remove context attribute at ChatViewModel.kt
  app/src/main/java/com/bitchat/android/ui/ChatViewModel.kt
Labels: enhancement

#142 Fix content padding in messages list
  app/src/main/java/com/bitchat/android/ui/ChatScreen.kt
  app/src/main/java/com/bitchat/android/ui/MessageComponents.kt
  app/src/main/java/com/bitchat/android/ui/SidebarComponents.kt
Labels: complete, UI/UX

#147 1. remove unused methods in MainActivity.kt
  app/src/main/java/com/bitchat/android/MainActivity.kt
Labels: complete
